### ISSUE TITLE
Integrate Proj4 string output

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/detectproj.mzk.cz#8]
Based on the implementation of @bayertom done at https://github.com/bayertom/libalgo/issues/2.

Once the integration is done - comment on the ticket above - with a report please.

We should also try to warp the original image with https://github.com/klokantech/gdal_georeferencer.
Just specify under `-srs` the proj string in quotes. It should produce visually the same results as the grid calculated by libalgo.

**Comment by dudaerich** [comment]
The integration is done, see for example http://staremapy.georeferencer.cz/map/kBXk9iDaTENJn8dxbmEtnL/201503081555-5Qhqqc/accuracy

**Comment by klokan** [comment]
Have you tried the gdal_georeferencer on a map from MZK @dudaerich?

**Comment by dudaerich** [comment]
Yes, I tried it just now. The program ends with error:

```
ERROR 6: Failed to initialize PROJ.4 with `+proj=bonne +lon_0=22.0398 +lat_1=0 +x_0=1490.46 +y_0=-1323.15 +a=2443.74 +b=2443.74 +units=m +no_defs '.
Traceback (most recent call last):
  File "gdal_georeferencer.py", line 1115, in <module>
    main(len(sys.argv), sys.argv)
  File "gdal_georeferencer.py", line 939, in main
    gcps = transform_gcps(georef['control_points'], srs)
  File "gdal_georeferencer.py", line 1001, in transform_gcps
    x, y, z = tr.TransformPoint(gcp['longitude'], gcp['latitude'], 0.0)
  File "/usr/lib64/python2.7/site-packages/osgeo/osr.py", line 753, in TransformPoint
    return _osr.CoordinateTransformation_TransformPoint(self, *args)
NotImplementedError: Wrong number of arguments for overloaded function 'CoordinateTransformation_TransformPoint'.
  Possible C/C++ prototypes are:
    TransformPoint(OSRCoordinateTransformationShadow *,double [3])
    TransformPoint(OSRCoordinateTransformationShadow *,double [3],double,double,double)
```

**Comment by dudaerich** [comment]
The detectproj mistakenly generates bonne projection with parameter lat_0. The correct parameter is lat_1. @bayertom was informed about this and he fixed it.

I tried to use gdal_georeferencer with following options, where thumbnail.jpg is thubmail of above map. However the out.tif doesn't contain graticule. @klokan, do I use gdal_georeferencer correctly?

```
python gdal_georeferencer.py -srs "proj +R=2443.74 +proj=bonne +lat_1=49.0278 +lon_0=22.0398 +x_0=1490.46 +y_0=-1323.15" kBXk9iDaTENJn8dxbmEtnL thumbnail.jpg out.tif
Fetching georeference ...
Warping ...
0...10...20...30...40...50...60...70...80...90...100 - done.
```
